services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:25.2.2
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=monic_db
    ports:
      - 9000:9000
      - 8123:8123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  monic-server:
    container_name: monic-server
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile
    environment:
      - MONIC_SERVER_HTTP_ADDR=:8000
      - MONIC_SERVER_GRPC_ADDR=:50051
      # gRPC TLS (опционально)
      # - MONIC_SERVER_TLS_CERT=/etc/monic/cert.pem
      # - MONIC_SERVER_TLS_KEY=/etc/monic/key.pem
      - MONIC_SERVER_SHARED_SECRET=secret
      - MONIC_SERVER_CLICKHOUSE_DSN=tcp://clickhouse:9000?database=monic_db
    # gRPC TLS (опционально)
    # volumes:
    #   - ./certs/cert.pem:/etc/monic/cert.pem:ro
    #   - ./certs/key.pem:/etc/monic/key.pem:ro
    ports:
      - 8000:8000
      - 50051:50051
    depends_on:
      - clickhouse
